apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: demo-cluster
  region: us-east-1
  version: "1.28"

nodeGroups:
  - name: ng-1
    instanceType: t3.micro
    desiredCapacity: 4
    volumeSize: 20 
    ssh:
      publicKeyPath: ~/.ssh/id_rsa_aws.pub