INSERT INTO "reviews" ("id", "score", "review", "created", "book_id", "user_id") VALUES
(1,	5,	'The story is presented as a first-person narrative using an unreliable narrator. He is a condemned man at the outset of the story.The narrator tells us that from an early age he has loved animals; he and his wife have many pets, including a large, beautiful black cat (as described by the narrator) named Pluto. This cat is especially fond of the narrator and vice versa. Their mutual friendship lasts for several years until the narrator becomes an alcoholic. One night, after coming home completely intoxicated, he believes the cat to be avoiding him. When he tries to seize it, the panicked cat bites the narrator, and in a fit of drunken rage he seizes the animal, pulls a pen-knife from his pocket, and deliberately gouges out the cats eye.',	'2020-05-23 19:25:34.654031',	5368,	1),
(2,	4,	'Clark classic novel is a compelling tale of four men who fear a marauding mountain lion but swear to conquer it. It is also a story of violent human emotions—love and hate, hope and despair—and of the perpetual conflict between good and evil.
"The reason why The Track of the Cat is a novel of the first rank is that its author says something of universal significance. The black panther has always been there since the beginning of mans existence in the world. It will always be there, looming over man and always to be hunted though never killed." —San Francisco Chronicle
"Mr. Clark knows his Nevada, as The Oxbow Incident proved, and he knows how to tell a good hunting story." —The New Yorker
"This is the real beauty of Walter Clarks masterful prose—its wonderful capacity to evoke from the homeliest circumstances the quality of grief and loneliness that exists deep in or under every human effort." —The New York Times
"Clarks story is continuously and wonderfully exciting. He is able to bring before the reader with extraordinary vividness the clash of stubborn wills in the snowbound ranch house, the unpopulated mountain landscape, the snow and cold, and above all, the hunt itself." —Yale Review',	'2018-04-12 00:36:42.427033',	10360,	3),
(3,	4,	'Clive Barker was born in Liverpool, England, the son of Joan Rubie (née Revill), a painter and school welfare officer, and Leonard Barker, a personnel director for an industrial relations firm. Educated at Dovedale Primary School and Quarry Bank High School, he studied English and Philosophy at Liverpool University and his picture now hangs in the entrance hallway to the Philosophy Department. It was in Liverpool in 1975 that he met his first partner, John Gregson, with whom he lived until 1986. Barkers second long-term relationship, with photographer David Armstrong, ended in 2009',	'2018-03-22 00:36:42.427033',	10330,	3),
(4,	4,	'Clive Barker is widely acknowledged as the master of nerve-shattering horror. The Hellbound Heart is one of his best, one of the most dead-frightening stories you are likely to ever read, a story of the human heart and all the great terrors and ecstasies within. It was also the book behind the cult horror film, Hellraiser.
In a quiet house on a quiet street Frank and Julia are having an affair. Not your ordinary affair. For Frank it began with his own insatiable sexual appetite, a mysterious lacquered box- and then an unhinged voyage through a netherworld of imaginable pleasures and unimaginable horror…',	'2019-06-20 00:36:42.427033',	10360,	2),
(5,	2,	'When Barry Fairbrother dies in his early forties, the town of Pagford is left in shock.
Pagford is, seemingly, an English idyll, with a cobbled market square and an ancient abbey, but what lies behind the pretty façade is a town at war.
Rich at war with poor, teenagers at war with their parents, wives at war with their husbands, teachers at war with their pupils ... Pagford is not what it first seems.',	'2018-03-22 00:36:42.427033',	10334,	2),
(6,	3,	'Jamaica in 1665 is a rough outpost of the English crown, a minor colony holding out against the vast supremacy of the Spanish empire. Port Royal, Jamaicas capital, a cut-throat town of taverns, grog shops, and bawdy houses, is devoid of Londons luxuries; life here can end swiftly with dysentery or a dagger in your back. But for Captain Charles Hunter it is a life that can also lead to riches, if he abides by the islands code. In the name of His Majesty King Charles II of England, gold in Spanish hands is gold for the taking. And law in the New World is made by those who take it into their hands.
Word in port is that the Spanish treasure galleon El Trinidad, fresh from New Spain, is stalled in nearby Matanceros harbor awaiting repairs. Heavily fortified, the impregnable Spanish outpost is guarded by the blood-swiller Cazalla, a favorite commander of King Philip IV himself. With the governors backing, Hunter assembles a roughneck crew to infiltrate the enemy island and commandeer the galleon, along with its fortune in Spanish gold. The raid is as perilous as the bloody legends of Matanceros suggest, and Hunter will lose more than one man before he finds himself on the islands shores, where dense jungle and the firepower of Spanish infantry are all that stand between him and the treasure.',	'1998-02-13 18:42:56.955997',	5396,	7);

INSERT INTO "users" ("id", "username", "name", "surname", "email", "created", "passwd") VALUES
(1,	'malunoemi',	'Amalia',	'Noemi',	'noe_malu@hotmail.com',	'2020-05-22 00:35:19.064835',	'testpasswd'),
(2,	'maurimem',	'Mauricio',	'Esteban',	'maurimem@gmail.com',	'2020-05-22 00:36:42.427033',	'pbkdf2:sha256:50000$VDa7lBtk$243f2ab1025daeab5cb0dcb13f6680f5bad80678e1bed3c66b216ff575774833'),
(3,	'nicopomoro',	'Nicolas',	'Pomoro',	'nicopomoro@classica.music',	'2020-05-23 01:50:06.586477',	'pbkdf2:sha256:50000$bDOm4QtQ$fe085cfab86231a88561af61126f55477ec5f22836cfda2e87ec417fce9aed1f'),
(4,	'mauri',	'Esteban',	'Quito',	'mauricio@gmail.com',	'2020-05-23 19:25:34.654031',	'pbkdf2:sha256:50000$cFmeMNSu$4dc44924d5f38c011e77e66d4b63a1aae496e511f249efc41589bdcf908062e6'),
(7,	'gumbo',	'Frank',	'Zappa',	'mail@gumbo.com',	'2020-05-24 18:42:56.955997',	'pbkdf2:sha256:50000$pvfdNeb2$839b76bef370d2d98d29122c5a62b62db9f4f51a2dc518ceaeb0a2b3848057d5');