version: '3.1'

services:

  pybooks:
    image: mauriciomem/pybooks:v0.1
    build: .
    environment:
       DATABASE_URL : "postgresql://postgres:${PGPASSWD}@dbpybooks:5432/booksdb"
    command: gunicorn --bind 0.0.0.0:5000 books:app
    ports:
      - 5000:5000
    networks:
      lab:

  dbpybooks:
    image: postgres:10
    restart: always
    environment:
      POSTGRES_PASSWORD: ${PGPASSWD}
      POSTGRES_DB: 'booksdb'
    volumes:
      - 'db-data:/var/lib/postgresql/data'
    ports:
      - '5432:5432'
    networks:
      lab:

  pgadmpybooks:
    image: adminer
    restart: always
    ports:
      - '8080:8080'
    networks:
      lab:

volumes:
  db-data:

networks:
  lab:
    driver: bridge
